- app/mci/cmd/create.go
- app/mci/pkg/gcp/healthcheck/fake_healthchecksyncer.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer_test.go
- app/mci/pkg/gcp/healthcheck/interfaces.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
- cmd/mci/app/mci.go
- cmd/mci/mci.go
@madhusudancs @csbell @G-Harmon
> Renaming imports to use updated path

- app/mci/cmd/create.go
- app/mci/pkg/gcp/healthcheck/fake_healthchecksyncer.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer_test.go
- app/mci/pkg/gcp/healthcheck/interfaces.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
Without the --force flag, healthchecks will be created, but not modified.
With it, healthchecks will be modified
CC @madhusudancs @csbell @nikhiljindal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/2)
> Add --force support for HealthChecks.

- app/mci/cmd/create.go
- app/mci/pkg/gcp/cloudinterface/interface.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go
One of the TODO from previous PR review was to add names to TODOs, so here they are :)
cc @G-Harmon
> Adding name to TODOs

- app/mci/pkg/gcp/backendservice/backendservicesyncer.go
- app/mci/pkg/gcp/backendservice/backendservicesyncer_test.go
- app/mci/pkg/gcp/backendservice/fake_backendservicesyncer.go
- app/mci/pkg/gcp/backendservice/interfaces.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
- app/mci/pkg/gcp/namer/namer.go
- app/mci/pkg/gcp/urlmap/fake_urlmapsyncer.go
- app/mci/pkg/gcp/urlmap/interfaces.go
- app/mci/pkg/gcp/urlmap/urlmapsyncer.go
- app/mci/pkg/gcp/urlmap/urlmapsyncer_test.go
This uses the backend services created in https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/3 to create the required URL map.
cc @G-Harmon @csbell @madhusudancs @bowei @nicksardo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/7)
> Adding code to create URLMaps

- app/mci/cmd/create.go
- app/mci/cmd/create_test.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- cmd/mci/mci.go
This is useful so that we can programmatically check the error codes from
creating Ingresses.
/cc @nikhiljindal @csbell @madhusudancs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/12)
> Switch from kubectl to the Go client for creating the Ingress.

- app/mci/cmd/cmd.go
- app/mci/cmd/create.go
- app/mci/cmd/create_test.go
- app/mci/cmd/delete.go
- app/mci/cmd/delete_test.go
- app/mci/pkg/gcp/backendservice/backendservicesyncer.go
- app/mci/pkg/gcp/backendservice/backendservicesyncer_test.go
- app/mci/pkg/gcp/backendservice/fake_backendservicesyncer.go
- app/mci/pkg/gcp/backendservice/interfaces.go
- app/mci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go
- app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer.go
- app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go
- app/mci/pkg/gcp/forwardingrule/interfaces.go
- app/mci/pkg/gcp/healthcheck/fake_healthchecksyncer.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer.go
- app/mci/pkg/gcp/healthcheck/healthchecksyncer_test.go
- app/mci/pkg/gcp/healthcheck/interfaces.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
- app/mci/pkg/gcp/targetproxy/fake_targetproxysyncer.go
- app/mci/pkg/gcp/targetproxy/interfaces.go
- app/mci/pkg/gcp/targetproxy/targetproxysyncer.go
- app/mci/pkg/gcp/targetproxy/targetproxysyncer_test.go
- app/mci/pkg/gcp/urlmap/fake_urlmapsyncer.go
- app/mci/pkg/gcp/urlmap/interfaces.go
- app/mci/pkg/gcp/urlmap/urlmapsyncer.go
- app/mci/pkg/gcp/urlmap/urlmapsyncer_test.go
Adding `mci delete` command to delete the load balancer created using `mci create`.
cc @csbell @G-Harmon @madhusudancs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/13)
> Adding logic to delete load balancer

- app/kubemci/cmd/cmd.go
- app/kubemci/cmd/create.go
- app/kubemci/cmd/create_test.go
- app/kubemci/cmd/delete.go
- app/kubemci/cmd/delete_test.go
- app/kubemci/cmd/getstatus.go
- app/kubemci/cmd/getstatus_test.go
- app/kubemci/cmd/version.go
- app/kubemci/cmd/version_test.go
It prints version of the form x.y.z with a + indicating if it is a release client or has dev changes on top.
> Adding a command to print client version

- app/kubemci/cmd/create.go
- app/kubemci/cmd/create_test.go
- app/kubemci/cmd/delete_test.go
- app/kubemci/cmd/version_test.go
Fixing errors from previous PR
cc @G-Harmon
> Fixing broken unit tests

- app/kubemci/cmd/create.go
@nikhiljindal @madhusudancs @G-Harmon @csbell
> Allow create to skip existing ingresses.

- app/kubemci/cmd/create.go
- app/kubemci/cmd/delete.go
- app/kubemci/cmd/getstatus.go
> Add [lbname] to the usage info for relevant commands.

- app/kubemci/cmd/version.go
Also added more detail to the description string.
cc @csbell @G-Harmon @madhusudancs @perotinus
> Updating the version to 0.1

- examples/zone-printer/README.md
- examples/zone-printer/ingress/nginx.yaml
Modify the supplied ingress manifest a little bit of templatization.
> Add a tutorial for zone-printer example.

- examples/zone-printer/README.md
This adds a step, after setting up the MCI, to try it out.
Also adds "-i" to the sed command, to make the change in-place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/54)
> Tutorial: Add a step to test out the new Ingress

- FAQs.md
cc @csbell @mdelio @G-Harmon @madhusudancs
> Adding an FAQ doc to answer common questions

- Makefile
Adding a Makefile with standard rules.
Makefile inspired from https://github.com/kubernetes/ingress-nginx/blob/b68feb9c590e2c11bdb098549f3208f80029daf7/Makefile
cc @csbell @G-Harmon @madhusudancs @perotinus
> Adding a Makefile

- app/kubemci/cmd/create.go
- app/kubemci/cmd/create_test.go
- app/kubemci/cmd/delete.go
- app/kubemci/cmd/delete_test.go
* -n or --namespace in create/delete
* --static-ip in create
Also, error out if user forgets to provide a static ip (either by flag or in their spec).
Addresses #33 and #19 
@nikhiljindal @madhusudancs @perotinus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/41)
> Add a few more usability flags and checks

- README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/64)
> Add Coverage widget to Readme.

- CONTRIBUTING.md
- FAQs.md
- README.md
Adding information on how to get started and how to contribute.
Also added links to the example, FAQs doc, contributing doc and the video demo.
cc @G-Harmon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/67)
> Adding more information to README

- demo/README.md
- demo/demo.sh
- demo/util.sh
Adding the demo script so that others can try it out as well.
cc @G-Harmon
> Adding the demo script

- app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go
- app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go
- app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go
- app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go
- app/kubemci/pkg/gcp/forwardingrule/interfaces.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
Similar to the other resources for which I've been adding support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/71)
> Add --force for forwarding Rule.

- demo/README.md
- demo/demo.sh
Factor out some variables. And add a loop to wget the IP so you can see when the LB is up and running.
cc @nikhiljindal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/74)
>  Updates to demo.sh: refactor to make it easier to share.

- app/kubemci/cmd/create.go
- app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/kubemci/pkg/gcp/urlmap/fake_urlmapsyncer.go
- app/kubemci/pkg/gcp/urlmap/interfaces.go
- app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go
- app/kubemci/pkg/gcp/urlmap/urlmapsyncer_test.go
Compares existing and desired UrlMaps when one already exists. Only changes an
existing one if the forceUpdate parameter is passed in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/70)
> Add --force support for URL Map.

- app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/kubemci/pkg/gcp/targetproxy/fake_targetproxysyncer.go
- app/kubemci/pkg/gcp/targetproxy/interfaces.go
- app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go
- app/kubemci/pkg/gcp/targetproxy/targetproxysyncer_test.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/76)
> Add --force support for Http Target Proxy; and fix little bug in forwarding rule syncer

- app/kubemci/pkg/gcp/firewallrule/fake_firewallrulesyncer.go
- app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer.go
- app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer_test.go
- app/kubemci/pkg/gcp/firewallrule/interfaces.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go
- app/kubemci/pkg/gcp/targetproxy/targetproxysyncer_test.go
- app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go
cc @csbell @nikhiljindal @madhusudancs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/77)
> Support for --force for firewall rules.

- app/kubemci/cmd/version.go
Bumping version to release 0.1.1
> Bumping version to 0.1.1

- README.md
Badges inspired from https://github.com/kubernetes/cluster-registry/blob/master/README.md.
cc @G-Harmon @csbell @perotinus @normanjoyner
> Adding links for more code health info

- README.md
> Updating the README to indicate that kubemci is GCP alpha

- app/kubemci/cmd/version.go
Updating the version to 0.2 in preparation for cutting 0.2 release
cc @G-Harmon
> Updating the version to 0.2

- test/e2e/cases/basic.go
- test/e2e/cases/utils.go
reviewers: @nikhiljindal 
cc: @csbell @madhusudancs 
Nikhil, I know you have a PR out for the e2e test now as well. It might be easier if this one goes in first? They both touch a lot of this file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/103)
> e2e test improvements: run "kubemci list" and more error checking

- examples/zone-printer/README.md
Update cluster version to latest "1.8.4.gke-1" since "1.8.0-gke.0" has been removed from the list.
> Update GCE cluster version in the README.md

- app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go
- app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/107
Have also refactored the tests to use multiple testcases in a single test rather than rewriting the test each time for each case. Added a test case for https as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/115)
> Fixing load balancer lister to not list https lb twice

- README.md
> Adding a link for feedback issue to README

- app/kubemci/cmd/create.go
- app/kubemci/cmd/create_test.go
- app/kubemci/cmd/delete.go
- app/kubemci/cmd/delete_test.go
- app/kubemci/pkg/ingress/ingresssyncer.go
- app/kubemci/pkg/ingress/ingresssyncer_test.go
- app/kubemci/pkg/ingress/interfaces.go
- app/kubemci/pkg/kubeutils/utils.go
This will fix #109. I've refactored the ingress creation and deletion into yet another syncer. Let me know if you'd like me to take another path.
Things to do before PR is complete:
> Update ingress with --force

- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- test/e2e/cases/basic.go
- test/e2e/cases/hcFromProbe.go
- test/e2e/cases/utils.go
- test/e2e/e2e.go
- testdata/e2e/hcFromProbe/app/hc-from-probe-dep.yaml
- testdata/e2e/hcFromProbe/app/hc-from-probe-svc.yaml
- testdata/e2e/hcFromProbe/ingress.yaml
Fixes #108. I refactored the basic case slightly so we could reuse part of the setup for other tests.
TODO:
> Health check from probe e2e test

- app/kubemci/pkg/gcp/sslcert/sslcertsyncer.go
- app/kubemci/pkg/gcp/sslcert/sslcertsyncer_test.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/46
Adding support for frontend HTTPS  with pre shared certs
> Adding support for frontend HTTPS with pre shared certs

- app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go
> Fixing a typo for healtcheck

- app/kubemci/cmd/version.go
> Updating kubemci version to 0.3

- troubleshooting.md
> Adding a troubleshooting doc with common errors

- README.md
Documenting known limitations.
cc @G-Harmon @csbell
> Adding a caveats section to Readme

- app/kubemci/cmd/create.go
- app/kubemci/cmd/create_test.go
- app/kubemci/cmd/delete.go
- app/kubemci/cmd/delete_test.go
- app/kubemci/pkg/gcp/utils/utils.go
- app/kubemci/pkg/kubeutils/utils.go
- app/kubemci/pkg/kubeutils/utils_test.go
- test/e2e/cases/basic.go
- test/e2e/cases/utils.go
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/80
cc @csbell @madhusudancs @G-Harmon
> Making --gcp-project optional by extracting project from gcloud

- app/kubemci/cmd/delete.go
Ref https://github.com/kubernetes/ingress-gce/issues/186
cc @G-Harmon 
Expect the tests to go green once this is merged: https://k8s-testgrid.appspot.com/sig-multicluster-kubemci#kubemci-ingress-conformance
They are failing right now due to leaked instance groups.
> Delete ingress from cluster after deleting the GCP resources

- app/kubemci/cmd/getstatus.go
- app/kubemci/cmd/getstatus_test.go
Adds missing functionality for getting GCP Project from gcloud settings, and adds unit tests for this.
cc @nikhiljindal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/172)
> Check gcloud for project, and add unit tests.

- app/kubemci/cmd/getstatus_test.go
- app/kubemci/cmd/list.go
- app/kubemci/cmd/list_test.go
I think this is the last PR for #80 .
cc @nikhiljindal @csbell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/176)
> "list" command: check gcloud-configured project if it's not set via flag

- app/kubemci/pkg/ingress/ingresssyncer.go
- app/kubemci/pkg/ingress/interfaces.go
- app/kubemci/pkg/kubeutils/utils.go
- app/kubemci/pkg/kubeutils/utils_test.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/61
Fixing lint error for pkg/ingress and pkg/kubeutils
cc @G-Harmon
> Fixing lint error for pkg/ingress and pkg/kubeutils

- app/kubemci/pkg/gcp/instances/instancegetter.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/kubemci/pkg/gcp/utils/utils.go
- app/kubemci/pkg/gcp/utils/utils_test.go
Ref #61
Fixing lint error for pkg/gcp/utils. Mostly about renaming Url -> URL
cc @G-Harmon
> Fixing lint errors in pkg/gcp/utils

- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
- app/kubemci/pkg/gcp/urlmap/fake_urlmapsyncer.go
- app/kubemci/pkg/gcp/urlmap/interfaces.go
- app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go
- app/kubemci/pkg/gcp/urlmap/urlmapsyncer_test.go
Ref #61
Fixing lint error for pkg/gcp/urlmap
cc @G-Harmon
> Fixing lint errors in pkg/gcp/urlmap

- app/kubemci/cmd/cmd.go
- app/kubemci/cmd/create.go
- app/kubemci/cmd/create_test.go
- app/kubemci/cmd/delete.go
- app/kubemci/cmd/delete_test.go
- app/kubemci/cmd/getstatus.go
- app/kubemci/cmd/getstatus_test.go
- app/kubemci/cmd/list.go
- app/kubemci/cmd/remove_clusters.go
- app/kubemci/cmd/version.go
Ref #61
Fixing lint error for `app/kubemci/cmd`
cc @G-Harmon
> Fixing lint for app/kubemci/cmd/

- app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go
- app/kubemci/pkg/gcp/backendservice/fake_backendservicesyncer.go
- app/kubemci/pkg/gcp/backendservice/interfaces.go
- app/kubemci/pkg/gcp/firewallrule/fake_firewallrulesyncer.go
- app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer.go
- app/kubemci/pkg/gcp/firewallrule/interfaces.go
- app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go
- app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go
- app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go
- app/kubemci/pkg/gcp/forwardingrule/interfaces.go
- app/kubemci/pkg/gcp/healthcheck/fake_healthchecksyncer.go
- app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go
- app/kubemci/pkg/gcp/healthcheck/interfaces.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
- app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
- app/kubemci/pkg/gcp/sslcert/fake_sslcertsyncer.go
- app/kubemci/pkg/gcp/sslcert/interfaces.go
- app/kubemci/pkg/gcp/sslcert/sslcertsyncer.go
- app/kubemci/pkg/gcp/targetproxy/fake_targetproxysyncer.go
- app/kubemci/pkg/gcp/targetproxy/interfaces.go
- app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go
- app/kubemci/pkg/gcp/targetproxy/targetproxysyncer_test.go
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/44
Ref #61
Fixing lint error for pkg/gcp
All sub packages in pkg/gcp have similar changes. The pattern was already reviewed for url map in https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/180.
Have hence combined all the changes in this single PR.
Apologies if its too big and hard to review :)
cc @G-Harmon
> Fixing lint errors in pkg/gcp

- app/kubemci/cmd/create_test.go
- app/kubemci/pkg/validations/fake_validations.go
This is a unit test verifying that errors from Validations.go are returned.
cc @nikhiljindal @madhusudancs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/188)
> Make sure that create.go propagates back validation errors correctly.

- .gitignore
As per discussion: https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/189#discussion_r180171321
cc @G-Harmon
> Adding .gitignore to ignore _output dir

- app/kubemci/cmd/version.go
Preparing for 0.4 launch.
cc @G-Harmon
> Updating kubemci version to 0.4

- README.md
> Updating the README to link to cloud.google.com docs

- examples/zone-printer/src/main.go
New functionality includes:
1. Configurable health check path + port
2. ability to kill health checks (i.e simulate health check failures)
3. Configurable version to simulate deployment upgrades.
4. root path which dumps useful information including version
Note that these changes introduce no new dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/235)
> Update zoneprinter code to include more functionality
