GoogleCloudPlatform/k8s-multicluster-ingress

app/mci/pkg/gcp/backendservice/backendservicesyncer.go, app/mci/pkg/gcp/backendservice/backendservicesyncer_test.go, app/mci/pkg/gcp/backendservice/fake_backendservicesyncer.go, app/mci/pkg/gcp/backendservice/interfaces.go, app/mci/pkg/gcp/healthcheck/fake_healthchecksyncer.go, app/mci/pkg/gcp/healthcheck/healthchecksyncer.go, app/mci/pkg/gcp/healthcheck/healthchecksyncer_test.go, app/mci/pkg/gcp/healthcheck/interfaces.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, glide.lock, glide.yaml
This uses the created health checks and instance groups annotation on the ingress to create the relevant backend service.
Verified by running `mci create` that it creates the backend service as expected.
cc @G-Harmon @madhusudancs @csbell
=> Adding code to create BackendServices

app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/mci/pkg/gcp/namer/namer.go, app/mci/pkg/gcp/targetproxy/fake_targetproxysyncer.go, app/mci/pkg/gcp/targetproxy/interfaces.go, app/mci/pkg/gcp/targetproxy/targetproxysyncer.go, app/mci/pkg/gcp/targetproxy/targetproxysyncer_test.go, app/mci/pkg/gcp/urlmap/fake_urlmapsyncer.go, app/mci/pkg/gcp/urlmap/urlmapsyncer.go, app/mci/pkg/gcp/urlmap/urlmapsyncer_test.go
This uses the URLMap created in https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/7 to create target proxies.
This PR contains logic to create HTTP proxies only. HTTPS proxies require additional logic of managing SSL certs. Will add support for that in a separate PR.
cc @bowei @nicksardo @csbell @G-Harmon @madhusudancs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/9)
=> Adding code to create Target http proxies

app/mci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/mci/pkg/gcp/forwardingrule/interfaces.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/mci/pkg/gcp/namer/namer.go, app/mci/pkg/gcp/targetproxy/fake_targetproxysyncer.go, app/mci/pkg/gcp/targetproxy/targetproxysyncer.go, app/mci/pkg/gcp/urlmap/fake_urlmapsyncer.go
Uses target proxies created in https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/9 to create forwarding rules.
Limitations:
* Requires the user to have reserved a static IP and specified it using the static ip annotation.
* Can only create http forwarding rules. Need to add logic for https.
Will fix the limitations in future PRs.
cc @bowei @nicksardo @csbell @G-Harmon @madhusudancs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/10)
=> Adding logic to create forwarding rules

app/mci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/mci/pkg/gcp/forwardingrule/interfaces.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/mci/pkg/gcp/targetproxy/fake_targetproxysyncer.go, app/mci/pkg/gcp/targetproxy/interfaces.go, app/mci/pkg/gcp/targetproxy/targetproxysyncer.go, app/mci/pkg/gcp/targetproxy/targetproxysyncer_test.go, glide.lock, vendor/k8s.io/ingress-gce/pkg/annotations/annotations.go, vendor/k8s.io/ingress-gce/pkg/backends/fakes.go, vendor/k8s.io/ingress-gce/pkg/controller/controller.go, vendor/k8s.io/ingress-gce/pkg/controller/controller_test.go, vendor/k8s.io/ingress-gce/pkg/controller/utils.go, vendor/k8s.io/ingress-gce/pkg/controller/utils_test.go, vendor/k8s.io/ingress-gce/pkg/healthchecks/fakes.go, vendor/k8s.io/ingress-gce/pkg/loadbalancers/fakes.go
Updated the code to detect when https was explicitly requested by user and generate a more meaningful error in that case rather than a generic always on warning.
Ran `glide update` to fetch latest code from kubernetes/ingress-gce to include https://github.com/kubernetes/ingress-gce/pull/58.
Also used the updated code to remove a bunch of TODOs for duplicated annotation keys.
cc @csbell @G-Harmon @madhusudancs
=> Fixing http-only target proxy and forwarding rule warning

app/mci/cmd/cmd.go, app/mci/cmd/create.go, app/mci/cmd/create_test.go, app/mci/cmd/delete.go, app/mci/cmd/getstatus.go, app/mci/cmd/getstatus_test.go, app/mci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/mci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/mci/pkg/gcp/forwardingrule/interfaces.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/mci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/mci/pkg/gcp/status/loadbalancerstatus.go
Adding a `get-status` command that prints information about the load balancer.
It prints the IP address and list of clusters that it is spread to.
Using ForwardingRule.Description to store this information.
cc @nicksardo @bowei @csbell @madhusudancs @G-Harmon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/14)
=> Adding logic for get status command

examples/zone-printer/app/nginx-dep.yaml, examples/zone-printer/app/nginx-svc.yaml, examples/zone-printer/app/zonefetch.yaml, examples/zone-printer/ingress/nginx.yaml
README to follow. This example contains an application that fetches the GCP zone the cluster is running in and serves that information on the paths `/`  or `/index.path`  via an nginx server.
=> Check in myzone example to the examples directory.

app/kubemci/cmd/create.go, app/kubemci/cmd/create_test.go, app/kubemci/cmd/delete.go, app/kubemci/cmd/delete_test.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
The code was fetching ingress only from the current-context cluster and using instance groups of only that cluster to create the backend service.
Fixed the code to now fetch the ingress from all clusters and hence include instance groups of all clusters.
cc @csbell @G-Harmon @madhusudancs @mdelio
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/23)
=> Updating the code to fetch instance groups annotation from ingress in all clusters

app/kubemci/cmd/create.go, app/kubemci/cmd/create_test.go, app/kubemci/cmd/delete.go, app/kubemci/cmd/delete_test.go
I considered adding tests for this, but the tests would have been checking that the end of the kubectl command had these string values, which didn't seem like a valuable test. I can add those tests if you want.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/30)
=> Add a flag to kubemci that takes a list of contexts.

app/kubemci/cmd/create.go, app/kubemci/cmd/create_test.go, app/kubemci/cmd/delete.go, app/kubemci/cmd/delete_test.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
While there, skip the double parsing of the ingress filename so a
single ingress object can be carried through each create/delete
operation.
@nikhiljindal @G-Harmon @madhusudancs @perotinus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/34)
=> Add defaulting to ingress namespace and annotations

app/kubemci/cmd/cmd.go, cmd/kubemci/kubemci.go
Fixes #26.
@madhusudancs @csbell @nikhiljindal @G-Harmon
=> Modify the cobra command setup to print a better help screen, and to enable -v (and other top level flags) to work with subcommands.

app/kubemci/cmd/create.go, app/kubemci/cmd/delete.go, app/kubemci/cmd/getstatus.go, app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go, app/kubemci/pkg/gcp/firewallrule/fake_firewallrulesyncer.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer_test.go, app/kubemci/pkg/gcp/firewallrule/interfaces.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/gcp/namer/namer.go, app/kubemci/pkg/gcp/networktags/fake_networktags.go, app/kubemci/pkg/gcp/networktags/interfaces.go, app/kubemci/pkg/gcp/networktags/networktags.go, app/kubemci/pkg/gcp/utils/utils.go, app/kubemci/pkg/gcp/utils/utils_test.go, examples/zone-printer/app/nginx-dep.yaml
Am creating a firewall rule per ingress unlike kube ingress controller which shares a single firewall rule for all ingresses. This is because the target nodes can be different for different multi cluster ingresses in this case, while in single kubernetes cluster case, all ingresses target the same nodes (all nodes in that cluster).
Also, I am fetching the first network tag from one instance in each cluster and using that in the forwarding rule, assuming that all nodes in that cluster has that same network tag. Verified that this is true for single and multi zone GCE and GKE clusters.
cc @csbell @madhusudancs @G-Harmon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s …
=> Adding code to create firewall rules

app/kubemci/cmd/create.go, app/kubemci/cmd/create_test.go, app/kubemci/cmd/delete.go, app/kubemci/cmd/delete_test.go
Just warns for now. We could add a "Press a key to continue..." prompt if we think this is important enough.
=> Make the kubeconfig flag required.

app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go
Updating the default health check path from `/healthz` to `/` to match that used by glbc kubernetes ingress controller: https://github.com/kubernetes/ingress-gce/blob/b0603c69382a39d097063eab8e3d9e30ca1cdf7b/cmd/glbc/main.go#L131.
This enables users to use their existing ingress yamls that work with single kubernetes cluster, with kubemci.
cc @csbell @G-Harmon @madhusudancs @mdelio
=> Updating the default health check path to match that used by glbc ingress controller

app/kubemci/cmd/create.go, app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go, app/kubemci/pkg/gcp/backendservice/backendservicesyncer_test.go, app/kubemci/pkg/gcp/backendservice/fake_backendservicesyncer.go, app/kubemci/pkg/gcp/backendservice/interfaces.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer_test.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
We only want to modify an existing BackendService if the user supplies the --force flag.
Note: I still need to debug the healthcheck comparison handling, before I can properly (manually) test this.
Reviewers: @nikhiljindal @csbell @madhusudancs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/27)
=> Add --force support to backendServiceSyncer.

app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go
Instead of checking for fields we explicitly care about, we switch to a
blacklist of fields that we ignore. This way, future fields are automatically
considered.
Also adds some more logging in error cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/55)
=> Future-proof Health Check comparison for healthchecksyncer.go.

Makefile
This target installs goveralls (via "go get") and then runs it to generate and upload test coverage data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/63)
=> Add a "coveralls" target for generating and uploading test coverage.

Makefile
I mainly want to run the tests against this PR, and probably not check it in.
cc @nikhiljindal @BenTheElder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/66)
=> Fixing the coveralls missing repotoken problem

app/kubemci/cmd/create.go, app/kubemci/cmd/create_test.go, app/kubemci/cmd/delete.go, app/kubemci/cmd/delete_test.go, app/kubemci/pkg/kubeutils/utils.go, app/kubemci/pkg/kubeutils/utils_test.go
Extracting out the code to create clients for kubeconfig contexts into a separate kubeutils pkg.
This removes code duplication in create.go and delete.go and also enables it to be reused at other places.
I am going to use the same code in my e2e test setup PR.
Have also added some more tests for failure cases for this code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/65)
=> Extracting out code to create clients for all kubeconfig contexts

app/kubemci/cmd/create_test.go
sometimes this test was failing because the list of clusters returned was in a different ordering than what we were using to compare.
cc @nikhiljindal @csbell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/75)
=> Fix flake in create_test.go: sort cluster list.

Makefile
…comments back to PR.
I think the best way to test this out is to put up this PR and see if it gets a coverage report.
The firewallrulesyncer.go change is just to make sure coveralls sees some Golang diff. I don't want to submit it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/78)
=> Add env vars to coverage target that will get Coveralls to post comments back to PR

app/kubemci/pkg/gcp/backendservice/backendservicesyncer_test.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer_test.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/utils/utils.go, app/kubemci/pkg/kubeutils/utils.go, app/kubemci/pkg/kubeutils/utils_test.go
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/59 and https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/60
I tried fixing `make lint` as well, but thats a huge change. Will fix it in a separate PR, mostly multiple PRs.
Once this merges will send a PR to run `make fmt vet` as part of our automated tests on each PR so that we do not regress.
=> Fixing code such that "make fmt vet" pass

Makefile, app/kubemci/pkg/kubeutils/utils.go, app/kubemci/pkg/kubeutils/utils_test.go, test/e2e/cases/basic.go, test/e2e/cases/utils.go, test/e2e/e2e.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/48
* Adding the setup to run e2e tests.
* There is a basic create test for now, that creates the example mci and validates that IP address becomes healthy eventually.
Once this is merged, next steps for future PRs:
* Run this e2e test continuously on prow.
* Add more tests.
* Fix TODOs sprinkled all through this code.
cc @csbell @G-Harmon @madhusudancs
=> Adding an e2e test to verify the example mci

app/kubemci/pkg/gcp/healthcheck/fake_healthchecksyncer.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer_test.go, app/kubemci/pkg/gcp/healthcheck/interfaces.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/kubeutils/utils.go
This PR is not ready but I wanted to open it because I would like some feedback on the approach before continuing. I tried reusing as much as possible from `ingress-gce`, however I chose to copy `GetProbe` and `getHTTPProbe` from `ingress-gce/controller/utils.go`. This is because the `GCETranslator` that was the receiver needed a `LoadBalancerController` to initialize which seemed like unnecessary bloat. One possible solution would be to refactor the code in `ingress-gce` to make it easier to reuse so we could avoid code duplication. I haven't bothered with the tests yet since I'm not sure if this is the way you'd want to implement this.
I tested the implementation manually by running and it works ~with one exception, sometimes it seems like even though the cached informer has been synced …
=> Get health check path from readiness probe

app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/gcp/namer/namer.go, app/kubemci/pkg/gcp/sslcert/fake_sslcertsyncer.go, app/kubemci/pkg/gcp/sslcert/interfaces.go, app/kubemci/pkg/gcp/sslcert/sslcertsyncer.go, app/kubemci/pkg/gcp/sslcert/sslcertsyncer_test.go, app/kubemci/pkg/gcp/targetproxy/fake_targetproxysyncer.go, app/kubemci/pkg/gcp/targetproxy/interfaces.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer_test.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/46
This is a step towards adding HTTPS support to kubemci.
It has the following main changes:
* Adding a SSLCertSyncer that manages certs for a given ingress
* Updating TargetProxySyncer to manage https target proxies as well.
In ingress-gce, Users can specify certs in 2 ways:
* Using ingress.Spec.TLS.SecretName
* Using ` ingress.gcp.kubernetes.io/pre-shared-cert` annotation.
SSLCertSyncer supports only the first for now. Will add support for the annotation in next PR.
Also note, that updating the secret will cause downtime for now, since it deletes and then recreates the ssl certificate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Adding code to create ssl cert from secret and create https target proxy

app/kubemci/cmd/cmd.go, app/kubemci/cmd/create.go, app/kubemci/cmd/list.go, app/kubemci/cmd/list_test.go, app/kubemci/cmd/version.go, app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/forwardingrule/interfaces.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/91)
=> kubemci list command: look for relevant global forwarding rules.

app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/forwardingrule/interfaces.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, test/e2e/cases/basic.go
Ref #46
Adding code to create an https forwarding rule. This completes the code to create an https ingress using secret certs.
We still need to add support for pre-shared certs. Also need to add a test for https ingress.
Ignore the first commit which is part of https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/92 (will rebase once it merges).
=> Adding code to create an https forwarding rule

app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
Forked from https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/100.
Fixing a bug in deleting SSL cert.
SSL cert can not be deleted before the target proxy using it is deleted.
Found while testing https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/100
cc @G-Harmon
=> Fixing a bug in deleting SSL certs

examples/zone-printer/ingress/https-ingress.yaml, test/e2e/cases/basic.go, test/e2e/cases/utils.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/46
Updating the e2e test script to verify an HTTPS ingress.
~~Also fixing a bug in deleting SSL cert in the process.
SSL cert can not be deleted before the target proxy using it is deleted.~~
cc @G-Harmon @csbell
=> Adding an e2e test to verify an HTTPS ingress

test/e2e/cases/basic.go
Currently the secret will be created in whatever clusters/namespaces you've configured in your normal kubeconfig.
=> Use correct kubeconfig when creating secret in e2e

app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/106
Updating `formatLoadBalancersList` to use kubectl's tab writer printer.
=> Updating kubemci list to use kubectl tab writer printer

app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go, app/kubemci/pkg/gcp/sslcert/sslcertsyncer.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go
We log "Updating existing resource" message twice - once before calling updateResource method and then again in the updateResource method.
Removing the call before calling the method and making it consistent for all resources.
cc @G-Harmon
=> Remove duplicate updating existing resource messages

app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go, test/e2e/cases/basic.go
Updating the test to verify that running kubemci create does not return an error.
This works for HTTP but fails for HTTPS due to https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/125
cc @G-Harmon
=> Verify that recreating the ingress works as expected

app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer_test.go, app/kubemci/pkg/gcp/instances/fake_instancegetter.go, app/kubemci/pkg/gcp/instances/instancegetter.go, app/kubemci/pkg/gcp/instances/interfaces.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/121
Renamed NetworkTagsGetter to InstanceGetter so that FirewallRuleSyncer can use it to fetch instances and then use the fetched instances to get both network tags and network name. This way we dont fetch instances twice.
cc @G-Harmon @nicksardo @csbell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/137)
=> Adding code to set the right network name while creating firewall rules

app/kubemci/pkg/gcp/sslcert/sslcertsyncer.go, app/kubemci/pkg/ingress/ingresssyncer.go, app/kubemci/pkg/kubeutils/utils.go, test/e2e/cases/basic.go
Fixing the issue where recreating https ingress was failing.
This was happening due to 2 reasons:
* kubemci thought that ingress changed even when it didnt. This was happening because the in cluster ingress had the instance groups annotation. Updated the code to ignore that annotation before comparing the ingresses.
* kubemci thought that SSL cert changed even when it didnt. This was because we were comparing the complete cert, which includes both the cert and the private key. But GCP returns a cert with empty private key (key is write only). Updated the code to compare the certificate only, which is what ingress-gce does as well: https://github.com/kubernetes/ingress-gce/blob/572e8e56a0c6ba15b0eac5ca870416c4c8fdc09c/pkg/loadbalancers/l7.go#L280
cc @csbell @madhusudancs @G-Harmon @bowei
=> Recreating HTTPS ingress should work without error

README.md, examples/zone-printer/https.md
Adding documentation for HTTPS ingresses
=> Adding documentation for HTTPS

app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go, app/kubemci/pkg/gcp/sslcert/sslcertsyncer.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go
ingress-gce recently changed to uniformly return "not found" errors
(instead of sometimes masking them). This change is needed before
revendoring ingress-gce.
Fixes issue #119 
cc @Nicksardo @csbell @nikhiljindal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/140)
=> Ignore "HTTP not found" errors when deleting GCP resources.

app/kubemci/cmd/cmd.go, app/kubemci/cmd/remove_clusters.go, app/kubemci/pkg/gcp/backendservice/backendservicesyncer.go, app/kubemci/pkg/gcp/backendservice/backendservicesyncer_test.go, app/kubemci/pkg/gcp/backendservice/fake_backendservicesyncer.go, app/kubemci/pkg/gcp/backendservice/interfaces.go, app/kubemci/pkg/gcp/firewallrule/fake_firewallrulesyncer.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer_test.go, app/kubemci/pkg/gcp/firewallrule/interfaces.go, app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/forwardingrule/interfaces.go, app/kubemci/pkg/gcp/instances/fake_instancegetter.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
As per https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/58, adding a new `kubemci remove-clusters` command that users can use to remove an existing MCI from some clusters.
Things left to be done:
* This still causes downtime. Filed https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/145 for that.
* This doesnt use --force yet.
* Adding more tests.
This PR has already become too big, so will do those in follow up PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/146)
=> Adding a remove-clusters command

app/kubemci/cmd/remove_clusters_test.go
Follow up to https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/146.
Adding tests to verify flags are validated as expected. This is similar to tests for other commands.
cc @csbell @G-Harmon @perotinus
=> Adding tests for validating remove-clusters command flags

app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/forwardingrule/interfaces.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/gcp/urlmap/fake_urlmapsyncer.go, app/kubemci/pkg/gcp/urlmap/interfaces.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer_test.go, app/kubemci/pkg/goutils/utils.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/145
Main changes:
* Stop storing LoadBalancerStatus on forwarding rules
* Start storing status on urlmaps
* Update List and GetStatus to read status from both forwarding rule and urlmap
* Update tests to test that both forwarding rule and urlmaps work fine with and without status.
We wont need special migration for existing MCI's.
Gradually as users update their MCI, status will be migrated from forwarding rule to urlmap.
User visible change:
If they run `kubemci create` again with existing ingress spec, they will expect it to not make any change.
With this, it will throw an error saying user needs to run the command with `--force` to update the forwarding rule and urlmap.
Will include it in release notes.
cc …
=> Store LoadBalancerStatus on urlmap instead of storing it on the forwarding rule

app/kubemci/pkg/gcp/backendservice/backendservicesyncer_test.go, app/kubemci/pkg/gcp/firewallrule/firewallrulesyncer_test.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer_test.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer_test.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer_test.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/155
Also added tests to ensure that we do not regress.
The tests wont fail however, until we update the ingress-gce fakes to return NotFound as expected (details in issue)
cc @G-Harmon @csbell
=> Fixing targetproxy deletion to not return an error when it does not exist

app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/gcp/status/loadbalancerstatus.go, app/kubemci/pkg/gcp/urlmap/fake_urlmapsyncer.go, app/kubemci/pkg/gcp/urlmap/interfaces.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer_test.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/58 (remove-clusters) and https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/145 (storing status on url map instead of forwarding rule).
Follow up to https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/146 which added a `kubemci remove-clusters` command. That PR updated the status stored on forwarding rule.
This PR updates that code to update the status on url map as well.
The status could be stored on forwarding rule (for old MCIs) or url map (for new MCIs).
=> Update remove-clusters to remove clusters from urlmaps status as well

app/kubemci/cmd/create.go, app/kubemci/pkg/gcp/healthcheck/healthchecksyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go, app/kubemci/pkg/kubeutils/utils.go, app/kubemci/pkg/validations/validations.go
For every Backend/Service in the Ingress, validates that each cluster
is using the same port number for its NodePort.
This covers some of the work needed for #53.
cc @nikhiljindal @csbell @bowei
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/148)
=> Basic --validate flag: Checks that NodePort is the same in each cluster.

app/kubemci/pkg/gcp/backendservice/fake_backendservicesyncer.go, app/kubemci/pkg/gcp/firewallrule/fake_firewallrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/fake_forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/gcp/urlmap/fake_urlmapsyncer.go, app/kubemci/pkg/gcp/urlmap/urlmapsyncer_test.go
Ref https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/58 and https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/145
Fixing TODOs from https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/151 and https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/149
Adding more unit tests for remove-clusters command.
Bulk of the PR is unit test changes, with minor bug fixes.
cc @csbell @G-Harmon @madhusudancs @perotinus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/158)
=> Adding more unit tests for remove-clusters

app/kubemci/cmd/delete.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go
Fixes https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/164
Adding a `--force` flag to kubemci delete to continue deletion even in case of errors.
Will add an e2e test as part of remove-clusters test (delete the mci after it has been removed from all clusters) 
cc @G-Harmon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/168)
=> Add --force to delete to allow users to force delete whatever can be deleted

app/kubemci/cmd/create.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/kubeutils/utils.go, app/kubemci/pkg/validations/validations.go, app/kubemci/pkg/validations/validations_test.go
We need a minimum of v1.8.1 for MCI to work.
This is for Issue #53 .
cc @nikhiljindal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/167)
=> --validate: Check server version for minimum version number.

app/kubemci/pkg/ingress/ingresssyncer.go, app/kubemci/pkg/ingress/ingresssyncer_test.go
Please ignore the first commit (server version validation), it's open PR #167 .
It seemed like the tests were already in pretty good shape for DeleteIngress. I added 2 more cases, and uncovered/fixed one small bug.
cc @csbell @nikhiljindal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/174)
=> IngressSyncer: Fix a bug in DeleteIngress and add more unit tests.

app/kubemci/pkg/validations/validations.go, app/kubemci/pkg/validations/validations_test.go, testdata/ingress.yaml
-Adds a default backend to testdata/ingress.yaml, needed to pass validation.
-Fixes a few lint errors in validations.go.
cc @nikhiljindal @csbell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/179)
=> Add a unit test for Validations.go: servicesNodePortsSame

Makefile
Fixing https://github.com/kubernetes/test-infra/pull/7563#issuecomment-379324371 to ensure that we fetch golint before running it.
cc @G-Harmon @BenTheElder @krzyzacy
=> Adding go get golint before running go lint

Makefile, scripts/check-gofmt.sh, test/e2e/cases/hcFromProbe.go
In order for gofmt to be blocking, we have to wrap it in a script that checks
for a non-empty return.  In the process, I switched from using "go list"
[dirs with _test.go files] to using all .go files that aren't in /vendor.
cc @madhusudancs @nikhiljindal
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/184)
=> Make gofmt check return an error, and check more .go files.

app/kubemci/cmd/create.go, app/kubemci/cmd/create_test.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer.go, app/kubemci/pkg/gcp/loadbalancer/loadbalancersyncer_test.go, app/kubemci/pkg/validations/fake_validations.go, app/kubemci/pkg/validations/interfaces.go, app/kubemci/pkg/validations/validations.go, app/kubemci/pkg/validations/validations_test.go
-Creates an interface for Validations and a fake Validator for unit tests.
-Adds a unit test for create.go:createIngressAndLoadBalancer.
cc @nikhiljindal @csbell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/183)
=> Move all validation to create.go and add more unit testing.

Makefile, app/kubemci/pkg/gcp/cloudinterface/interface.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer.go, app/kubemci/pkg/gcp/forwardingrule/forwardingrulesyncer_test.go, app/kubemci/pkg/gcp/instances/fake_instancegetter.go, app/kubemci/pkg/gcp/instances/instancegetter.go, app/kubemci/pkg/gcp/instances/interfaces.go, app/kubemci/pkg/gcp/namer/namer.go, app/kubemci/pkg/gcp/status/loadbalancerstatus.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer.go, app/kubemci/pkg/gcp/targetproxy/targetproxysyncer_test.go, cmd/kubemci/app/kubemci.go, scripts/check-golint.sh, test/e2e/cases/basic.go, test/e2e/cases/hcFromProbe.go, test/e2e/cases/utils.go
This adds a wrapper script to error-out if there are lint problems.
This only checks packages with _test.go files. We could extend it to all .go files in the code base (but there are a few more lint errors to fix).
Another commit fixes up 2 existing lint errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/k8s-multicluster-ingress/186)
=> Make lint errors blocking, and fix a few last lint problems

app/kubemci/cmd/remove_clusters.go
Making remove-clusters code consistent with delete code.
If updating GCP resources failed, then return an error right away rather than continuing. Continue only if --force=true.
This also fixes our failing e2e test which is failing with leaking instance group which is the same issue as the one we had for delete: https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/169.
If we delete the ingress from cluster before GCP resources (in particular the backend service) is deleted, then the ingress controller does not delete the instance group.
This fixes that.
cc @G-Harmon
=> Delete ingress from cluster when updating GCP resources failed only if force=true

Makefile
It has been failing with:
W0803 19:24:01.716] Bad response status from coveralls: 422
W0803 19:24:01.716] {"message":"Couldn't find a repository matching this job.","error":true}
W0803 19:24:01.718] make: *** [coveralls] Error 1
W0803 19:24:01.719] Traceback (most recent call last):
W0803 19:24:01.719]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0803 19:24:01.719]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0803 19:24:01.719]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0803 19:24:01.719]     check(*cmd)
W0803 19:24:01.719]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0803 19:24:01.720]     subprocess.check_call(cmd)
W0803 19:24:01.720]   File …
=> Fix Coveralls invocation, by adding '-service "prow"' 

.gitignore, Makefile
This PR addresses Issue https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/190
My guess is that the way Goveralls [merges profiles](https://github.com/mattn/goveralls/blob/e68c968003c2db2ad7cdf07b3c012c5ab12248a7/gocover.go#L32-L34) may have been affected by one of the Go releases. 
This PR uses the functionality of [Go 1.10](https://golang.org/doc/go1.10#test) to create the coverprofile. 
>The go test -coverpkg flag now interprets its argument as a comma-separated list of patterns to match against the dependencies of each test, not as a list of packages to load anew.
There are some existing issues open with how `coverpkg` works which may change the behavior of `go test` coverage reports in the future:
- https://github.com/golang/go/issues/23910
- …
=> Address Coveralls Reported Coverage Level

README.md, examples/zone-printer/README.md
Updated a link on the main readme to point back to the correct link (https://cloud.google.com/kubernetes-engine/docs/how-to/kubemci)
Added instructions for installing kubemci itself in the example readme.
=> Documentation - Link & Instructions 

app/kubemci/pkg/validations/validations.go
Fixing build failure due to missing formatting directive in glog.Infof call.
The relevant error is as follows:
```
app/kubemci/pkg/validations/validations.go:186: Verbose.Infof call has arguments but no formatting directives
```
Example run with the failure: https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/GoogleCloudPlatform_k8s-multicluster-ingress/199/pull-kubernetes-multicluster-ingress-test/278/
cc @G-Harmon
=> Fixing build failure due to missing formatting directives
